### ISSUE TITLE
build failed???

### ISSUE THREAD

**Issue by anhtlauncher** [Snoworange420/Mousse#5]
:skull: 
![image](https://user-images.githubusercontent.com/99712037/197347157-c7863350-5707-447f-98cf-2b99b99207f4.png)
how

**Comment by Snoworange420** [comment]
![0C4038F1-555B-462A-8772-DCE07005882D](https://user-images.githubusercontent.com/110935731/197366654-e6af4970-0fe9-4d6d-9d98-7b758ebb066c.jpeg)

hope it helps 😳

**Comment by anhtlauncher** [comment]
uh i have jdk 17 but i cant upgrade gradle, it keep no error message

**Comment by anhtlauncher** [comment]
> ![0C4038F1-555B-462A-8772-DCE07005882D](https://user-images.githubusercontent.com/110935731/197366654-e6af4970-0fe9-4d6d-9d98-7b758ebb066c.jpeg)
> 
> hope it helps 😳

uh i have jdk 17 but i cant upgrade gradle, it keep show no error message

**Comment by Snoworange420** [comment]
You need jdk 8 💀

**Comment by anhtlauncher** [comment]
lol ok it worked i forgot to change xd

**Comment by Snoworange420** [comment]
Bruv
