### ISSUE TITLE
nah just wanna ask something

### ISSUE THREAD

**Issue by anhtlauncher** [Snoworange420/Mousse#6]
32k aura is auto 32k? and why it doesnt work sometimes :/

**Comment by Snoworange420** [comment]
32kaura is just a killaura with high cps that works when you have 32k sharpness item in your main hand.

auto32k is a module that sets up 32k combat with hopper, and dispenser32k is a module that sets up 32k combat with dispensers.

**Comment by Snoworange420** [comment]
Dispenser32k should work fine

**Comment by anhtlauncher** [comment]
> 32kaura is just a killaura with high cps that works when you have 32k sharpness item in your main hand.
> 
> auto32k is a module that sets up 32k combat with hopper, and dispenser32k is a module that sets up 32k combat with dispensers.
> 
> hope this helped you.

oh 32k aura is just killaura? ok. And can u make uh the module save the keybind for next time launch game?

**Comment by Snoworange420** [comment]
Use the command &save and &load.

**Comment by Snoworange420** [comment]
If its broken I will fix it in a next update 💀
